### ISSUE TITLE
Game Selection View

### ISSUE THREAD

**Issue by JamieWindfox** [JamieWindfox/PAPI#17]
List of already created games

- [x] Table of created Games with Genre, Date of last Session (#35 permanent save files required)
- [ ] Delete Game Button for each row
- [x] Load Game Button for each row (Link to #19 SessionOverview)
- [x] Return Button (Link to #61 Start View)
- [x] New Game Button (Link to #20 GameCreatorStartView)
- [x] Scrollbar
- [x] Translated Text
    - saved_games_label
    - genre_label
    - date_label
    - return_button
    - game_creator_button
    - design of game
    - date of game creation
    - date of last save
    - load_game_button
    - delete_game_button
