### ISSUE TITLE
Game Creator Start View

### ISSUE THREAD

**Issue by JamieWindfox** [JamieWindfox/PAPI#20]
Create a new Game, select a genre
- [x] Name of Game Master
- [x] Show unique Game ID
- [ ] Send unique Game ID to Server
- [x] Genre Dropdown
- [x] Genre Description
- [ ] If design isn't fitting the genre, give user the tip, that they can change the design in the options
- [x] Cancel Button (Link to #17 GameSelectionView)
- [ ] Create & Return Button (Link to #17 Game Selection View)
- [ ] Create & Start Button (Link to #19 Session Start View)
- [ ] Save New Game in file
- [ ] Translated Text

**Comment by JamieWindfox** [comment]
Must be adapted to new network protocol
