### ISSUE TITLE
NPC Creator Basics View

### ISSUE THREAD

**Issue by JamieWindfox** [JamieWindfox/PAPI#29]
- [ ] Table of Characteristics, changing with the selected species
- [ ] plus Button for each characteristic
- [ ] minus button for each characteristic
- [ ] Dropdown for Species
- [ ] woundThreshold
- [ ] plus button for wound threshold
- [ ] minus button for wound threshold
- [ ] soak
- [ ] plus button for soak
- [ ] minus button for soak
- [ ] strain Threshold
- [ ] plus strain threshold button
- [ ] minu strain threshold button
- [ ] (if minion) Minion group size (default = 3)
- [ ] plus minion group size button
- [ ] minus minion group size button
- [ ] appearance Button (Link to ApppearanceCustomizationView)
- [ ] description input field
- [ ] skills button (Link to #12 SkillSelectionView)
- [ ] talent button (Link to #13 TalentSelectionView)
- [ ] abilities button (Link to AbilitySelectionView)
- [ ] equipment button (Link to NpcEquipmentSelectionView)
- [ ] motivation button (Link to #10 MotivationSelectionView)
- [ ] create npc button (Link to caller with saving)
- [ ] cancel button (Link to caller without saving)
- [ ] Language Text
