### ISSUE TITLE
[Mobile Device] Session Overview

### ISSUE THREAD

**Issue by JamieWindfox** [JamieWindfox/PAPI#57]
Gives an Overview of the currently running Game Session
- [ ] At first start open Popup (#21 Story Point Distribution Popup)
- [ ] Genre of Game
- [ ] Table of Players and their Characters (with Name, Species, Career, collected Exp of this session)
- [ ] Show Button for each row (Link to #22 Character Overview View)
- [ ] Add 1 Exp Button for each Player Character
- [ ] Quit Button (Popup: Save Game? Y/N, then shut down Application)
- [ ] NPCs Button (Link to #23 NPC List View)
- [ ] Items Button (Link to Item List View)
- [ ] Properties Button(Link to GM Properties List View)
- [ ] Options Button (Link to #15 Options View)
- [ ] Language Text
